# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1IGHFeeerghzwHuj8MA7O9zN388jKAp
"""

# q1_nlp.py
"""
Requires:
  pip install spacy
  python -m spacy download en_core_web_sm
"""

import spacy

nlp = spacy.load("en_core_web_sm", disable=["parser","ner"])  # we only need tokenizer, tagger, lemmatizer
nlp.enable_pipe("tagger")

text = "John enjoys playing football while Mary loves reading books in the library."

doc = nlp(text)

# 1. Tokenize (spaCy doc)
tokens = [t for t in doc]

# 2. Remove stopwords and punctuation, and lemmatize
filtered = []
for t in tokens:
    if t.is_stop or t.is_punct or t.like_num:
        continue
    # keep only alphabetic tokens (drop punctuation, etc.)
    if not t.is_alpha:
        continue
    # 3. Keep only verbs and nouns (POS tags)
    # spaCy POS tags: t.pos_ is coarse-grained (e.g., 'VERB', 'NOUN', 'PROPN', ...)
    if t.pos_ in ("VERB", "NOUN", "PROPN"):
        filtered.append((t.text, t.lemma_, t.pos_))

# Output
print("Tokens (text, lemma, POS):")
for item in filtered:
    print(item)

# q2_ner_pronoun_warning.py
"""
Requires:
  pip install spacy
  python -m spacy download en_core_web_sm
"""

import spacy

nlp = spacy.load("en_core_web_sm")  # includes NER

text = "Chris met Alex at Apple headquarters in California. He told him about the new iPhone launch."

doc = nlp(text)

# Named Entities
print("Named Entities (text, label):")
for ent in doc.ents:
    print(f"{ent.text}  —  {ent.label_}")

# Pronoun ambiguity check (simple heuristic)
pronouns = {"he","she","they","him","her","them","his","hers","their","it","its"}
tokens_lower = [t.text.lower() for t in doc]
if any(p in tokens_lower for p in pronouns):
    print("\nWarning: Possible pronoun ambiguity detected!")